### ISSUE TITLE
ImportError: cannot import name 'NAPosition' from 'postalign.models.na_position' after calling postalign

### ISSUE THREAD

**Issue by WilliamZekaiWang** [hivdb/post-align#5]
Hi, after running the `setup.py` script and calling postalgin I receive the following error

```
Traceback (most recent call last):
  File "/home/will/miniconda3/envs/venv/bin/postalign", line 33, in <module>
    sys.exit(load_entry_point('post-align==0.1.0', 'console_scripts', 'postalign')())
  File "/home/will/miniconda3/envs/venv/bin/postalign", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/will/miniconda3/envs/venv/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/will/miniconda3/envs/venv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/will/miniconda3/envs/venv/lib/python3.10/site-packages/post_align-0.1.0-py3.10-linux-x86_64.egg/postalign/entry.py", line 1, in <module>
  File "/home/will/miniconda3/envs/venv/lib/python3.10/site-packages/post_align-0.1.0-py3.10-linux-x86_64.egg/postalign/cli.py", line 11, in <module>
  File "/home/will/miniconda3/envs/venv/lib/python3.10/site-packages/post_align-0.1.0-py3.10-linux-x86_64.egg/postalign/processor.py", line 2, in <module>
  File "/home/will/miniconda3/envs/venv/lib/python3.10/site-packages/post_align-0.1.0-py3.10-linux-x86_64.egg/postalign/models/__init__.py", line 1, in <module>
  File "/home/will/miniconda3/envs/venv/lib/python3.10/site-packages/post_align-0.1.0-py3.10-linux-x86_64.egg/postalign/models/sequence.py", line 14, in <module>
ImportError: cannot import name 'NAPosition' from 'postalign.models.na_position' (/home/will/.cache/Python-Eggs/post_align-0.1.0-py3.10-linux-x86_64.egg-tmp/postalign/models/na_position.cpython-310-x86_64-linux-gnu.so)
```

I tried changing the import to import * instead of just NAPosition in `sequences.py` and `_sequences.py` but that only resulted in another in `_sequences.py` which states NAPosition doesn't exist

**Comment by philiptzou** [comment]
Hi @WilliamZekaiWang! Have you attempted to launch a Python console and execute the command `from postalign.models.na_position import NAPosition`? Additionally, I noticed that you utilized Py3.10, which I haven't personally tested with PostAlign.

This `Dockerfile` includes installation steps for PostAlign that are guaranteed to work: https://github.com/hivdb/sierra/blob/main/Dockerfile#L24-L30. Could you please verify if any steps were missed during your installation process? Thanks.

**Comment by WilliamZekaiWang** [comment]
I ran it under py 3.9.5 and the cython version 0.32.29 and it worked in the python console! Thank you for the help
