### ISSUE TITLE
TypeError: Argument 'value' has incorrect type (expected list, got tuple)

### ISSUE THREAD

**Issue by WilliamZekaiWang** [hivdb/post-align#6]
Hello, 

While trying to do a subprocess call on postalign, I got the following error
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/new2/bin/postalign", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 1675, in invoke
    sub_ctx = cmd.make_context(
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/root/miniconda3/envs/new2/lib/python3.9/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
TypeError: Argument 'value' has incorrect type (expected list, got tuple)
```
This was with python version `3.9.0` and cython version `0.29.32`, with all steps followed on the docker file.

However, the weird thing is that I managed to get postalign running previously on another environment with identical installs. Redoing the installation steps on that environment doesn't yield this issue and leads to postalign running normally.

**Comment by WilliamZekaiWang** [comment]
> 1. change `core.py` in where click is installed `~/lib/python3.9/site-packages/click/` on `line 2322`:
> 
> ```
> value = self.callback(ctx, self, value)
> ```
> 
> into
> 
> ```
> if type(value) == tuple:
>     value = list(value)
> value = self.callback(ctx, self, value)
> ```
> 
> 2. change `save_json.py` file in `~/lib/python3.9/site-packages/postalign/processors/` on `line 25`:
> 
> ```
> for one in value + ('$$', ):
> ```
> 
> into
> 
> ```
> for one in value + ['$$', ]:
> ```

This fixes the issue above on my local system, but it would need to change the `click` package, which is probably not ideal

**Comment by philiptzou** [comment]
@WilliamZekaiWang I think the issue you encountered has just been fixed yesterday: https://github.com/hivdb/post-align/commit/8e2ee118261987208c17add6cef5c1270e325a4c
